### ISSUE TITLE
For now, The server isn't work

### ISSUE THREAD

**Issue by dutn158** [tonilopezmr/Game-of-Thrones#1]
i have just tested.
`failed to connect to ec2-52-18-202-124.eu-west-1.compute.amazonaws.com/52.18.202.124 (port 3000) after 10000ms`

**Comment by tonilopezmr** [comment]
Hello @dutn158 ^^

Yes, in d7efb176d787d3c1a1e77f0a453aa1be29ffbbd0 the problem is solved 💃
